authenticate/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from authenticate.views import CustomLoginView, CustomLogoutView, CustomSignUpView

app_name = "authenticate"

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name=""), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name=""), name='password_change_done'),
    path('password_reset', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('signup/', CustomSignUpView.as_view(), name='signup')
]

djangochat/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('authenticate.urls')),
    path('users/', include('user.urls')),
    path('', include('chatroom.urls')),
    path('friends/', include('friends.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

friends/urls.py
from django.urls import path

from friends.views import RequestFriendView, AcceptRequestFriend, DeclineRequestFriend, FriendListView

app_name = "friends"

urlpatterns = [
    path('add/<int:receiver_user_id>/', RequestFriendView.as_view(),  name='friend_action'),
    path('accept/', AcceptRequestFriend.as_view(), name='accept_friend'),
    path('decline/', DeclineRequestFriend.as_view(), name='decline_friend'),
    path('list/', FriendListView.as_view(), name='friend_list'),
]

user/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from user.views import UserProfileView, SearchUserView

app_name = "user"

urlpatterns = [
    path('profile/<int:user_id>/', UserProfileView.as_view(), name='user_profile'),
    path('ajax/search/', SearchUserView.as_view(), name='ajax_search'),
]

templates/accounts/login.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
Login Chat
{% endblock title %}

{% block cssblock %}
    <link rel="stylesheet" href="{% static 'css/auth.css' %}?version=1">
    <style>
        .container {
            background-image: url("{% static 'img/bg.png' %}");
        }
    </style>
{% endblock cssblock %}


{% block content %}
<div class="container">
    <div class="container-left">
    </div>
    <div class="container-right">
        <div class="auth-form">
            <div class="auth-form__logo">
                <img class="auth-form__logo-img" src="{% static 'img/simplechat-logo.png' %}" alt="Logo chat">
            </div>
    
            <div class="auth-form__header">
                <h2 class="auth-form__heading">Welcome Back!</h2>
                <p class="auth-form__description">Please login to chat, thank you.</p>
            </div>

            <div class="auth-form__form">
                <form method="post" action="{% url 'authenticate:login' %}">
                    {% csrf_token %}
                    
                    {% if form.errors %}
                        <div class="auth-form__msg">
                            <strong>Error!</strong>Your username and password didn't match. Please try again.
                        </div>
                    {% endif %}
                    <div class="auth-form__group">
                        <!-- {{ form.username.label_tag }} -->
                        {{ form.username|add_class:"auth-form__input"|attr:"placeholder: "}}
                        <label for="{{ form.username.auto_id }}" class="auth-form__label">{{ form.username.label }}</label>
                        <i class="fa-solid fa-user auth-form__icon"></i>
                    </div>
    
                    <div class="auth-form__group">
                        <!-- {{ form.password.label_tag }} -->
                        {{ form.password|add_class:"auth-form__input"|attr:"placeholder: "}}
                        <label for="{{ form.password.auto_id }}" class="auth-form__label">{{ form.password.label }}</label>
                        <i class="fa-solid fa-key auth-form__icon"></i>
                    </div>
                    <div class="auth-form__reset-pass">
                        <a class="auth-form__reset-pass-link" href="{% url 'authenticate:password_reset' %}">Lost password?</a>
                    </div>
                    <button class="btn btn--primary auth-form__submit-btn" type="submit" value="login">Login</button>
                    <input type="hidden" name="next" value="{{ next }}">
                </form>
            </div>
            <div class="auth-form__social">
                <a href="" class="btn btn--with-icon">
                    <img class="btn--icon-img" src="{% static 'img/ico-google.svg' %}" alt="LogoGoogle">
                    <span class="btn--icon-text">Sign in with Google</span>
                </a>
            </div>
            <div class="auth-form__signup-redirect">
                <p class="auth-form__signup-text">Don't have an account yet?</p>
                <a href="{% url 'authenticate:signup' %}" class="auth-form__signup-link">Sign Up</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/profile.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
Profile {{request.user.username}}
{% endblock title %}

{% block cssblock %}
    <link rel="stylesheet" href="{% static 'css/profile.css' %}?version=1">
    <style>
        .container {
            background-image: url("{% static 'img/bg.png' %}");
        }
    </style>
{% endblock cssblock %}

{% block header %}
    {% include 'pages/header.html' %}
{% endblock header %}

{% block content %}

<div class="container-profile">
    <div class="grid">
        <div class="grid__row">
            <div class="grid__col-3"></div>
            <div class="grid__col-6">
                <div class="profile">
                    <img src="{{ user_profile.profile_image.url }}" alt="" class="profile__img">
                    <div class="profile__info">
                        <p class="profile__info-username">{{ user_profile.username }}</p>
                        <p class="profile__info-email">{{ user_profile.email }}</p>
                    </div>
                    <div class="profile__action">
                        <form class="profile__action" action="{% url 'friends:friend_action' user_profile.pk %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{{ request.path }}">
                            {% if RELATIONSHIP == 0 %}
                                <button name="profile_action" value="edit_profile" class="btn btn--with-icon">
                                    <i class=".btn--icon-img fa-solid fa-user-pen"></i>
                                    <p class="btn--icon-text">Edit Profile</p> 
                                </button>
                             {% else %}
                                <button name="profile_action" value="message" class="btn btn--with-icon">
                                    <i class=".btn--icon-img fa-solid fa-message"></i>
                                    <p class="btn--icon-text">Message</p>
                                </button>
                                {% if RELATIONSHIP == 2 %}
                                    <button name="profile_action" value="add_friend" class="btn btn--with-icon">
                                        <i class=".btn--icon-img fa-solid fa-user-plus"></i>
                                        <p class="btn--icon-text">Add Friend</p> 
                                    </button>
                                {% elif RELATIONSHIP == 1 %}
                                    <button name="profile_action" value="unfriend" class="btn btn--with-icon">
                                        <i class=".btn--icon-img fa-solid fa-user-xmark"></i>
                                        <p class="btn--icon-text">UnFriend</> 
                                    </button>
                                {% endif %}
                            {% endif %}
                        </form>                        
                    </div>
                    <div class="profile__extra">
                        <a href="javascript:void(0);" class="profile__extra-link" id="friend_list_btn">
                            <p class="profile__extra-link__count">
                                {{user_friend_list.count}}
                            </p>
                            <p class="profile__extra-link__title">
                                Friends
                            </p>
                        </a>
                        
                        {% if RELATIONSHIP == 0  %}
                            <a href="javascript:void(0);" class="profile__extra-link" id="request_list_btn">
                                <p class="profile__extra-link__count">
                                    {{user_request_list.count}}
                                </p>
                                <p class="profile__extra-link__title">
                                    Friends Request
                                </p>
                            </a> 
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="grid__col-3">
            </div>
        </div>
    </div>
</div>
    
{% endblock content %}

{% block modal_content %}
    <div class="extra-list">
        <div class="extra-list__header">
            <h3 id="extra-list__title">Request Friend</h3>
            <span id="close_list_btn">x</span>
        </div>
        <div class="extra-list__body">
            <ul id="friend_request_list" class="extra-list__list">
                
                {% for request_friend in user_request_list %}
                <li class="extra-list__item" >
                    <img src="{{ request_friend.sender.profile_image.url }}" alt="" class="extra-list__item-img">
                    <h4 class="extra-list__item-username">{{ request_friend.sender.username }}</h4>
                    <div class="extra-action">
                        <button onclick="accept_friend_request('{{request_friend.pk }}')" id="accept_friend{{ request_friend.pk }}" class="btn extra-action__btn"><i class="fa-solid fa-circle-check"></i></button>
                        <button onclick="decline_friend_request('{{request_friend.pk }}')" class="btn extra-action__btn"><i class="fa-solid fa-circle-xmark"></i></button>
                    </div>
                </li>
                {% endfor %}
                    
            </ul>
            <ul id="friend_list_list" class="extra-list__list">
                
                {% for friend in user_friend_list %}
                <li class="extra-list__item" >
                    <img src="{{ friend.profile_image.url }}" alt="" class="extra-list__item-img">
                    <h4 class="extra-list__item-username">{{ friend.username }}</h4>
                </li>
                {% endfor %}
                    
            </ul>
        </div>
    </div>
{% endblock modal_content %}


{% block jsblock %}
    <script src="{% static 'js/profile.js' %}"></script>
    <script>
        function accept_friend_request(request_id) {
            var url = '{% url "friends:accept_friend" %}'
            $.ajax({
                type: 'GET',
                url: url,
                data: {"request_id": request_id},
                success: function (response) {
                    alert(response["success"]);
                },
                error: function (response) {
                    console.log(response)
                }
            })
        }

        function decline_friend_request(request_id) {
            var url = '{% url "friends:decline_friend" %}'
            $.ajax({
                type: 'GET',
                url: url,
                data: {"request_id": request_id},
                success: function (response) {
                    alert(response["success"]);
                },
                error: function (response) {
                    console.log(response)
                }
            })
        }
    </script>
{% endblock jsblock %}
    

templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}Sign Page{% endblock title %}

{% block content %} 
    <h2>Sign Page</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
        <br><br>
    </form>
{% endblock content %}