authenticate/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from authenticate.views import CustomLoginView, CustomLogoutView, CustomSignUpView

app_name = "authenticate"

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name=""), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name=""), name='password_change_done'),
    path('password_reset', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('signup/', CustomSignUpView.as_view(), name='signup')
]

chatroom/urls.py
from django.urls import path

from chatroom.views import ChatRoomView, ChatRoomBlankView, IndexPageView


app_name = "chatroom"
urlpatterns = [
    path('', IndexPageView.as_view(), name='index'),
    path('chatroom/home/', ChatRoomBlankView.as_view(), name='home'),
    path('chatroom/<int:room_id>/chat/', ChatRoomView.as_view(), name='main_chat'),
    # path('<int:friend_id>/', FindRoomView.as_view(), name="find_room")
]

djangochat/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('authenticate.urls')),
    path('users/', include('user.urls')),
    path('', include('chatroom.urls')),
    path('friends/', include('friends.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

friends/urls.py
from django.urls import path

from friends.views import RequestFriendView, AcceptRequestFriend, DeclineRequestFriend, FriendListView

app_name = "friends"

urlpatterns = [
    path('add/<int:receiver_user_id>/', RequestFriendView.as_view(),  name='friend_action'),
    path('accept/', AcceptRequestFriend.as_view(), name='accept_friend'),
    path('decline/', DeclineRequestFriend.as_view(), name='decline_friend'),
    path('list/', FriendListView.as_view(), name='friend_list'),
]

user/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from user.views import UserProfileView, SearchUserView

app_name = "user"

urlpatterns = [
    path('profile/<int:user_id>/', UserProfileView.as_view(), name='user_profile'),
    path('ajax/search/', SearchUserView.as_view(), name='ajax_search'),
]

templates/pages/footer.html
<footer class="footer">
    
</footer>

templates/pages/header.html
{% load static %}
<header class="header">
    <div class="grid">
        <nav class="header__navbar">
            <div class="header__navbar-left">
                <div class="header__navbar-logo">
                    <a href="{% url 'chatroom:home' %}" class="header__navbar-logo-link">
                        <img class="header__navbar-logo-img" src="{% static 'img/simplechat-logo.png' %}" alt="Logo web">
                    </a>
                </div>
                <ul class="header__navbar-list header__navbar-menu">
                    <li id="navbar-chat" class="header__navbar-item">
                        <a href="{% url 'chatroom:home' %}" class="header__navbar-item-link">
                            <i class="header__navbar-item-logo fa-solid fa-message"></i>
                            Chat
                        </a>
                    </li>
                    <li id="navbar-contact" class="header__navbar-item">
                        <a href="{% url 'friends:friend_list' %}" class="header__navbar-item-link">
                            <i class="header__navbar-item-logo fa-solid fa-address-book"></i>
                            Contact
                        </a>
                    </li>
                    <li id="navbar-notification" class="header__navbar-item">
                        <a href="#" class="header__navbar-item-link">
                            <i class="header__navbar-item-logo fa-solid fa-bell"></i>
                            Notification
                        </a>
                    </li>
                    <li id="navbar-setting" class="header__navbar-item">
                        <a href="#" class="header__navbar-item-link">
                            <i class="header__navbar-item-logo fa-solid fa-bars"></i>
                            Setting
                        </a>
                    </li>
                </ul>
            </div>
            <div class="header__navbar-right">
                {% if user.is_authenticated %}
                    <img class="header__navbar-item-link header__navbar-profile-avatar" alt="">
                    <div id="header-profile-menu" class="header__navbar-profile">
                        <span class="header__navbar-item-link header__navbar-profile-username">{{request.user.username}}</span>
                        <p class="header__navbar-profile-status">Active</p>
                    </div>
                    <div id="user-menu" class="user-menu">
                        <a href="{% url 'user:user_profile' user.id %}" class="user-item user-item--top">
                            <i class="user-item__icon fa-regular fa-user"></i>
                            <span class="user-item__text">My Profile</span>
                        </a>
                        <a href="" class="user-item user-item--center">
                            <i class="user-item__icon fa-solid fa-gear"></i>
                            <span class="user-item__text">Setting</span>
                        </a>
                        <a href="{% url 'authenticate:logout' %}" class="user-item user-item--bot">
                            <i class="user-item__icon fa-solid fa-right-from-bracket"></i>
                            <span class="user-item__text">Logout</span>
                        </a>
                    </div>
                {% else %}
                    <ul class="header__navbar-list">
                        <li class="header__navbar-item">
                            <a href="" class="header__navbar-item-link header__navbar-signup">SignUp</a>
                        </li>
                        <li class="header__navbar-item">
                            <a href="" class="header__navbar-item-link header__navbar-login">Login</a>
                        </li>
                    </ul>
                {% endif %}
            </div>
        </nav>
    </div>

</header>

templates/pages/home.html
{% extends 'base.html' %}

{% block title %}Home Chat{% endblock title %}

{% block header %}
    {% include 'pages/header.html' %}
{% endblock header %}

{% block content %}

<h1>Home page.</h1>
<a href="{% url 'authenticate:logout' %}">Logout</a>


{% endblock content %}

templates/pages/navbar.html
<nav class="navbar">
    
</nav>